-- ============================================================
--  UniversalPOS — V1 Initial Schema
--  Oracle 21c / Flyway Migration
--  Author: UniversalPOS
--  Date: 2026-03-17
-- ============================================================

-- ── SEQUENCES ─────────────────────────────────────────────────
CREATE SEQUENCE TENANT_SEQ      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EMPLOYEE_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE CUSTOMER_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PRODUCT_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DISCOUNT_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TRANSACTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TXN_ITEM_SEQ    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE RECEIPT_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE AUDIT_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ── TENANTS ───────────────────────────────────────────────────
CREATE TABLE TENANTS (
    TENANT_ID       NUMBER          NOT NULL,
    COMPANY_NAME    VARCHAR2(100)   NOT NULL,
    TENANT_SLUG     VARCHAR2(50)    NOT NULL,
    LOGO_URL        VARCHAR2(500),
    BRAND_COLOR     VARCHAR2(7),
    RECEIPT_HEADER  VARCHAR2(200),
    RECEIPT_FOOTER  VARCHAR2(200),
    TAX_RATE        NUMBER(5,4)     DEFAULT 0.0825  NOT NULL,
    CURRENCY_CODE   VARCHAR2(3)     DEFAULT 'USD'   NOT NULL,
    TIMEZONE        VARCHAR2(50)    DEFAULT 'America/Chicago' NOT NULL,
    ACTIVE          NUMBER(1)       DEFAULT 1       NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_TENANTS         PRIMARY KEY (TENANT_ID),
    CONSTRAINT UQ_TENANT_SLUG     UNIQUE (TENANT_SLUG),
    CONSTRAINT CK_TAX_RATE        CHECK (TAX_RATE BETWEEN 0 AND 1),
    CONSTRAINT CK_TENANT_ACTIVE   CHECK (ACTIVE IN (0, 1))
);

-- ── EMPLOYEES ─────────────────────────────────────────────────
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID     NUMBER          NOT NULL,
    TENANT_ID       NUMBER          NOT NULL,
    FIRST_NAME      VARCHAR2(60)    NOT NULL,
    LAST_NAME       VARCHAR2(60)    NOT NULL,
    EMAIL           VARCHAR2(150)   NOT NULL,
    PASSWORD_HASH   VARCHAR2(255)   NOT NULL,
    ROLE            VARCHAR2(20)    NOT NULL,
    EMPLOYEE_NUMBER VARCHAR2(20),
    ACTIVE          NUMBER(1)       DEFAULT 1    NOT NULL,
    LAST_LOGIN_AT   TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_EMPLOYEES       PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_EMP_TENANT      FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID),
    CONSTRAINT UQ_EMP_EMAIL       UNIQUE (EMAIL, TENANT_ID),
    CONSTRAINT CK_EMP_ROLE        CHECK (ROLE IN ('CASHIER', 'MANAGER', 'ADMIN')),
    CONSTRAINT CK_EMP_ACTIVE      CHECK (ACTIVE IN (0, 1))
);

-- ── CUSTOMERS ─────────────────────────────────────────────────
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID         NUMBER          NOT NULL,
    TENANT_ID           NUMBER          NOT NULL,
    FIRST_NAME          VARCHAR2(60)    NOT NULL,
    LAST_NAME           VARCHAR2(60)    NOT NULL,
    EMAIL               VARCHAR2(150),
    PHONE               VARCHAR2(20),
    LOYALTY_CARD_NUMBER VARCHAR2(20),
    LOYALTY_TIER        VARCHAR2(20)    DEFAULT 'NONE' NOT NULL,
    LOYALTY_POINTS      NUMBER(10)      DEFAULT 0      NOT NULL,
    DATE_OF_BIRTH       DATE,
    EMAIL_OPT_IN        NUMBER(1)       DEFAULT 0      NOT NULL,
    NOTES               VARCHAR2(500),
    ACTIVE              NUMBER(1)       DEFAULT 1      NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP,
    CONSTRAINT PK_CUSTOMERS           PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT FK_CUST_TENANT         FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID),
    CONSTRAINT UQ_CUST_EMAIL          UNIQUE (EMAIL, TENANT_ID),
    CONSTRAINT UQ_LOYALTY_CARD        UNIQUE (LOYALTY_CARD_NUMBER),
    CONSTRAINT CK_LOYALTY_TIER        CHECK (LOYALTY_TIER IN ('NONE','BRONZE','SILVER','GOLD','PLATINUM')),
    CONSTRAINT CK_LOYALTY_PTS         CHECK (LOYALTY_POINTS >= 0),
    CONSTRAINT CK_CUST_ACTIVE         CHECK (ACTIVE IN (0, 1)),
    CONSTRAINT CK_CUST_EMAIL_OPT      CHECK (EMAIL_OPT_IN IN (0, 1))
);

-- ── PRODUCTS ──────────────────────────────────────────────────
CREATE TABLE PRODUCTS (
    PRODUCT_ID      NUMBER          NOT NULL,
    TENANT_ID       NUMBER          NOT NULL,
    SKU             VARCHAR2(50)    NOT NULL,
    NAME            VARCHAR2(150)   NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    PRICE           NUMBER(10,2)    NOT NULL,
    COST            NUMBER(10,2),
    CATEGORY        VARCHAR2(100),
    SUBCATEGORY     VARCHAR2(100),
    BRAND           VARCHAR2(100),
    BARCODE         VARCHAR2(50),
    STOCK_QTY       NUMBER(10)      DEFAULT 0  NOT NULL,
    REORDER_POINT   NUMBER(10)      DEFAULT 5,
    TAXABLE         NUMBER(1)       DEFAULT 1  NOT NULL,
    ACTIVE          NUMBER(1)       DEFAULT 1  NOT NULL,
    IMAGE_URL       VARCHAR2(500),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_PRODUCTS        PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_PROD_TENANT     FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID),
    CONSTRAINT UQ_SKU_TENANT      UNIQUE (SKU, TENANT_ID),
    CONSTRAINT CK_PROD_PRICE      CHECK (PRICE >= 0),
    CONSTRAINT CK_PROD_TAXABLE    CHECK (TAXABLE IN (0, 1)),
    CONSTRAINT CK_PROD_ACTIVE     CHECK (ACTIVE IN (0, 1))
);

-- ── DISCOUNTS ─────────────────────────────────────────────────
CREATE TABLE DISCOUNTS (
    DISCOUNT_ID         NUMBER          NOT NULL,
    TENANT_ID           NUMBER          NOT NULL,
    NAME                VARCHAR2(100)   NOT NULL,
    DESCRIPTION         VARCHAR2(300),
    DISCOUNT_TYPE       VARCHAR2(30)    NOT NULL,
    VALUE               NUMBER(10,2)    NOT NULL,
    MIN_PURCHASE        NUMBER(10,2),
    LOYALTY_TIER_REQUIRED VARCHAR2(20),
    COUPON_CODE         VARCHAR2(30),
    MAX_USES            NUMBER(10),
    TIMES_USED          NUMBER(10)      DEFAULT 0  NOT NULL,
    START_DATE          DATE,
    END_DATE            DATE,
    REQUIRES_MANAGER    NUMBER(1)       DEFAULT 0  NOT NULL,
    ACTIVE              NUMBER(1)       DEFAULT 1  NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_DISCOUNTS       PRIMARY KEY (DISCOUNT_ID),
    CONSTRAINT FK_DISC_TENANT     FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID),
    CONSTRAINT CK_DISC_TYPE       CHECK (DISCOUNT_TYPE IN ('PERCENT','FIXED_AMOUNT','LOYALTY_TIER','COUPON_CODE','EMPLOYEE')),
    CONSTRAINT CK_DISC_VALUE      CHECK (VALUE > 0),
    CONSTRAINT CK_DISC_MANAGER    CHECK (REQUIRES_MANAGER IN (0, 1)),
    CONSTRAINT CK_DISC_ACTIVE     CHECK (ACTIVE IN (0, 1))
);

-- ── TRANSACTIONS ──────────────────────────────────────────────
CREATE TABLE TRANSACTIONS (
    TXN_ID              NUMBER          NOT NULL,
    TENANT_ID           NUMBER          NOT NULL,
    CUSTOMER_ID         NUMBER,
    EMPLOYEE_ID         NUMBER          NOT NULL,
    RECEIPT_NUMBER      VARCHAR2(30)    NOT NULL,
    SUBTOTAL            NUMBER(10,2)    NOT NULL,
    DISCOUNT_AMOUNT     NUMBER(10,2)    DEFAULT 0  NOT NULL,
    TAX_AMOUNT          NUMBER(10,2)    NOT NULL,
    TOTAL               NUMBER(10,2)    NOT NULL,
    PAYMENT_METHOD      VARCHAR2(20)    NOT NULL,
    AMOUNT_TENDERED     NUMBER(10,2),
    CHANGE_DUE          NUMBER(10,2),
    STATUS              VARCHAR2(20)    DEFAULT 'IN_PROGRESS' NOT NULL,
    TXN_TYPE            VARCHAR2(20)    DEFAULT 'SALE' NOT NULL,
    ORIGINAL_TXN_ID     NUMBER,
    LOYALTY_POINTS_EARNED NUMBER(10)   DEFAULT 0,
    NOTES               VARCHAR2(500),
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT        TIMESTAMP,
    CONSTRAINT PK_TRANSACTIONS    PRIMARY KEY (TXN_ID),
    CONSTRAINT FK_TXN_TENANT      FOREIGN KEY (TENANT_ID)   REFERENCES TENANTS(TENANT_ID),
    CONSTRAINT FK_TXN_CUSTOMER    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_TXN_EMPLOYEE    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CONSTRAINT UQ_RECEIPT_NUMBER  UNIQUE (RECEIPT_NUMBER),
    CONSTRAINT CK_TXN_PAYMENT     CHECK (PAYMENT_METHOD IN ('CASH','CREDIT_CARD','DEBIT_CARD','GIFT_CARD','SPLIT')),
    CONSTRAINT CK_TXN_STATUS      CHECK (STATUS IN ('IN_PROGRESS','COMPLETED','VOIDED','REFUNDED')),
    CONSTRAINT CK_TXN_TYPE        CHECK (TXN_TYPE IN ('SALE','RETURN','EXCHANGE','VOID'))
);

-- ── TRANSACTION ITEMS ─────────────────────────────────────────
CREATE TABLE TRANSACTION_ITEMS (
    ITEM_ID             NUMBER          NOT NULL,
    TXN_ID              NUMBER          NOT NULL,
    PRODUCT_ID          NUMBER          NOT NULL,
    QTY                 NUMBER(10)      NOT NULL,
    UNIT_PRICE          NUMBER(10,2)    NOT NULL,
    DISCOUNT_APPLIED    NUMBER(10,2)    DEFAULT 0,
    LINE_TOTAL          NUMBER(10,2)    NOT NULL,
    DISCOUNT_LABEL      VARCHAR2(100),
    CONSTRAINT PK_TXN_ITEMS       PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_ITEM_TXN        FOREIGN KEY (TXN_ID)     REFERENCES TRANSACTIONS(TXN_ID),
    CONSTRAINT FK_ITEM_PRODUCT    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT CK_ITEM_QTY        CHECK (QTY > 0)
);

-- ── RECEIPTS ──────────────────────────────────────────────────
CREATE TABLE RECEIPTS (
    RECEIPT_ID      NUMBER          NOT NULL,
    TXN_ID          NUMBER          NOT NULL,
    TENANT_ID       NUMBER          NOT NULL,
    EMAIL_ADDRESS   VARCHAR2(150),
    EMAILED         NUMBER(1)       DEFAULT 0  NOT NULL,
    EMAILED_AT      TIMESTAMP,
    PRINTED         NUMBER(1)       DEFAULT 0  NOT NULL,
    PRINTED_AT      TIMESTAMP,
    PDF_PATH        VARCHAR2(500),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_RECEIPTS        PRIMARY KEY (RECEIPT_ID),
    CONSTRAINT FK_RECEIPT_TXN     FOREIGN KEY (TXN_ID)    REFERENCES TRANSACTIONS(TXN_ID),
    CONSTRAINT FK_RECEIPT_TENANT  FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID),
    CONSTRAINT UQ_RECEIPT_TXN     UNIQUE (TXN_ID),
    CONSTRAINT CK_RECEIPT_EMAIL   CHECK (EMAILED IN (0, 1)),
    CONSTRAINT CK_RECEIPT_PRINT   CHECK (PRINTED IN (0, 1))
);

-- ── AUDIT LOG ─────────────────────────────────────────────────
CREATE TABLE AUDIT_LOG (
    LOG_ID          NUMBER          NOT NULL,
    TENANT_ID       NUMBER          NOT NULL,
    EMPLOYEE_ID     NUMBER,
    EMPLOYEE_NAME   VARCHAR2(120),
    ACTION          VARCHAR2(50)    NOT NULL,
    ENTITY_TYPE     VARCHAR2(50),
    ENTITY_ID       NUMBER,
    DETAILS         VARCHAR2(2000),
    IP_ADDRESS      VARCHAR2(45),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDIT_LOG       PRIMARY KEY (LOG_ID)
);

-- ── INDEXES ───────────────────────────────────────────────────
-- NOTE: Oracle automatically creates an index for every UNIQUE constraint.
-- We only create ADDITIONAL indexes here for non-unique columns that need
-- fast lookup. Do NOT re-index columns already covered by UNIQUE constraints:
--   UQ_CUST_EMAIL    covers (EMAIL, TENANT_ID)
--   UQ_LOYALTY_CARD  covers (LOYALTY_CARD_NUMBER)
--   UQ_SKU_TENANT    covers (SKU, TENANT_ID)
--   UQ_RECEIPT_NUMBER covers (RECEIPT_NUMBER)
--   UQ_RECEIPT_TXN   covers (TXN_ID) on RECEIPTS

-- Customer lookups — phone and tenant are NOT covered by unique constraints
CREATE INDEX IDX_CUST_PHONE      ON CUSTOMERS (PHONE, TENANT_ID);
CREATE INDEX IDX_CUST_TENANT     ON CUSTOMERS (TENANT_ID);

-- Product lookups — barcode and category are NOT unique-constrained
CREATE INDEX IDX_PROD_BARCODE    ON PRODUCTS (BARCODE, TENANT_ID);
CREATE INDEX IDX_PROD_CATEGORY   ON PRODUCTS (CATEGORY, TENANT_ID);
CREATE INDEX IDX_PROD_TENANT     ON PRODUCTS (TENANT_ID);

-- Transaction lookups
CREATE INDEX IDX_TXN_CUSTOMER    ON TRANSACTIONS (CUSTOMER_ID);
CREATE INDEX IDX_TXN_TENANT_DATE ON TRANSACTIONS (TENANT_ID, CREATED_AT);
CREATE INDEX IDX_TXN_EMPLOYEE    ON TRANSACTIONS (EMPLOYEE_ID);
CREATE INDEX IDX_TXN_STATUS      ON TRANSACTIONS (STATUS, TENANT_ID);

-- Audit trail
CREATE INDEX IDX_AUDIT_TENANT    ON AUDIT_LOG (TENANT_ID, CREATED_AT);
CREATE INDEX IDX_AUDIT_EMPLOYEE  ON AUDIT_LOG (EMPLOYEE_ID);