-- ============================================================
--  UniversalPOS — V3 Inventory Management Schema
--  Oracle 21c / Flyway Migration
--  Adds: Suppliers, Purchase Orders, Inventory Adjustments,
--        Stock Counts
-- ============================================================
-- ── SUPPLIERS ─────────────────────────────────────────────────
-- Companies you order inventory from (distributors, manufacturers, reps)
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID     NUMBER          NOT NULL,
    TENANT_ID       NUMBER          NOT NULL,
    NAME            VARCHAR2(150)   NOT NULL,
    CONTACT_NAME    VARCHAR2(120),
    EMAIL           VARCHAR2(150),
    PHONE           VARCHAR2(30),
    ADDRESS         VARCHAR2(300),
    WEBSITE         VARCHAR2(200),
    ACCOUNT_NUMBER  VARCHAR2(50),
    PAYMENT_TERMS   VARCHAR2(100),
    LEAD_TIME_DAYS  NUMBER(5)       DEFAULT 7,
    NOTES           VARCHAR2(1000),
    ACTIVE          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_SUPPLIERS       PRIMARY KEY (SUPPLIER_ID),
    CONSTRAINT FK_SUPP_TENANT     FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID),
    CONSTRAINT CK_SUPP_ACTIVE     CHECK (ACTIVE IN (0, 1))
);

-- Link products to their supplier(s)
-- A product can have multiple suppliers; one is marked preferred
CREATE TABLE PRODUCT_SUPPLIERS (
    ID              NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    SUPPLIER_ID     NUMBER          NOT NULL,
    SUPPLIER_SKU    VARCHAR2(100),
    UNIT_COST       NUMBER(10,2),
    MIN_ORDER_QTY   NUMBER(10)      DEFAULT 1,
    PREFERRED       NUMBER(1)       DEFAULT 0 NOT NULL,
    ACTIVE          NUMBER(1)       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_PROD_SUPP       PRIMARY KEY (ID),
    CONSTRAINT FK_PS_PRODUCT      FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_PS_SUPPLIER     FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT UQ_PROD_SUPP       UNIQUE (PRODUCT_ID, SUPPLIER_ID),
    CONSTRAINT CK_PS_PREFERRED    CHECK (PREFERRED IN (0, 1)),
    CONSTRAINT CK_PS_ACTIVE       CHECK (ACTIVE IN (0, 1))
);

-- ── PURCHASE ORDERS ───────────────────────────────────────────
-- Orders placed to suppliers to restock inventory
CREATE TABLE PURCHASE_ORDERS (
    PO_ID           NUMBER          NOT NULL,
    TENANT_ID       NUMBER          NOT NULL,
    SUPPLIER_ID     NUMBER          NOT NULL,
    CREATED_BY      NUMBER          NOT NULL,
    PO_NUMBER       VARCHAR2(30)    NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'DRAFT' NOT NULL,
    ORDER_DATE      DATE,
    EXPECTED_DATE   DATE,
    RECEIVED_DATE   DATE,
    SUBTOTAL        NUMBER(10,2)    DEFAULT 0 NOT NULL,
    TAX_AMOUNT      NUMBER(10,2)    DEFAULT 0 NOT NULL,
    SHIPPING_COST   NUMBER(10,2)    DEFAULT 0 NOT NULL,
    TOTAL           NUMBER(10,2)    DEFAULT 0 NOT NULL,
    NOTES           VARCHAR2(1000),
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_PURCHASE_ORDERS PRIMARY KEY (PO_ID),
    CONSTRAINT FK_PO_TENANT       FOREIGN KEY (TENANT_ID)   REFERENCES TENANTS(TENANT_ID),
    CONSTRAINT FK_PO_SUPPLIER     FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    CONSTRAINT FK_PO_EMPLOYEE     FOREIGN KEY (CREATED_BY)  REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CONSTRAINT UQ_PO_NUMBER       UNIQUE (PO_NUMBER),
    CONSTRAINT CK_PO_STATUS       CHECK (STATUS IN ('DRAFT','SUBMITTED','CONFIRMED','PARTIAL','RECEIVED','CANCELLED'))
);

CREATE TABLE PURCHASE_ORDER_ITEMS (
    ITEM_ID         NUMBER          NOT NULL,
    PO_ID           NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    QTY_ORDERED     NUMBER(10)      NOT NULL,
    QTY_RECEIVED    NUMBER(10)      DEFAULT 0 NOT NULL,
    UNIT_COST       NUMBER(10,2)    NOT NULL,
    LINE_TOTAL      NUMBER(10,2)    NOT NULL,
    NOTES           VARCHAR2(500),
    CONSTRAINT PK_PO_ITEMS        PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_POI_PO          FOREIGN KEY (PO_ID)       REFERENCES PURCHASE_ORDERS(PO_ID),
    CONSTRAINT FK_POI_PRODUCT     FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT CK_POI_QTY         CHECK (QTY_ORDERED > 0),
    CONSTRAINT CK_POI_RECV        CHECK (QTY_RECEIVED >= 0)
);

-- ── INVENTORY ADJUSTMENTS ─────────────────────────────────────
-- Manual stock count corrections, damage write-offs, theft, returns to supplier
CREATE TABLE INVENTORY_ADJUSTMENTS (
    ADJ_ID          NUMBER          NOT NULL,
    TENANT_ID       NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    EMPLOYEE_ID     NUMBER          NOT NULL,
    ADJUSTMENT_TYPE VARCHAR2(30)    NOT NULL,
    QTY_BEFORE      NUMBER(10)      NOT NULL,
    QTY_CHANGE      NUMBER(10)      NOT NULL,
    QTY_AFTER       NUMBER(10)      NOT NULL,
    REASON          VARCHAR2(500),
    REFERENCE_ID    NUMBER,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_INV_ADJ         PRIMARY KEY (ADJ_ID),
    CONSTRAINT FK_ADJ_TENANT      FOREIGN KEY (TENANT_ID)   REFERENCES TENANTS(TENANT_ID),
    CONSTRAINT FK_ADJ_PRODUCT     FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_ADJ_EMPLOYEE    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CONSTRAINT CK_ADJ_TYPE        CHECK (ADJUSTMENT_TYPE IN (
        'SALE','RETURN','PO_RECEIPT','MANUAL_ADD','MANUAL_REMOVE',
        'DAMAGE','THEFT','EXPIRY','TRANSFER','COUNT_CORRECTION'
    ))
);

-- ── STOCK COUNTS ──────────────────────────────────────────────
-- Physical inventory count sessions (full or partial)
CREATE TABLE STOCK_COUNTS (
    COUNT_ID        NUMBER          NOT NULL,
    TENANT_ID       NUMBER          NOT NULL,
    CREATED_BY      NUMBER          NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'IN_PROGRESS' NOT NULL,
    COUNT_TYPE      VARCHAR2(20)    DEFAULT 'FULL' NOT NULL,
    CATEGORY_FILTER VARCHAR2(100),
    STARTED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    COMPLETED_AT    TIMESTAMP,
    NOTES           VARCHAR2(500),
    CONSTRAINT PK_STOCK_COUNTS    PRIMARY KEY (COUNT_ID),
    CONSTRAINT FK_SC_TENANT       FOREIGN KEY (TENANT_ID)  REFERENCES TENANTS(TENANT_ID),
    CONSTRAINT FK_SC_EMPLOYEE     FOREIGN KEY (CREATED_BY) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    CONSTRAINT CK_SC_STATUS       CHECK (STATUS IN ('IN_PROGRESS','COMPLETED','CANCELLED')),
    CONSTRAINT CK_SC_TYPE         CHECK (COUNT_TYPE IN ('FULL','PARTIAL','CATEGORY'))
);

CREATE TABLE STOCK_COUNT_ITEMS (
    ITEM_ID         NUMBER          NOT NULL,
    COUNT_ID        NUMBER          NOT NULL,
    PRODUCT_ID      NUMBER          NOT NULL,
    QTY_EXPECTED    NUMBER(10),
    QTY_COUNTED     NUMBER(10),
    VARIANCE        NUMBER(10),
    COUNTED_BY      NUMBER,
    COUNTED_AT      TIMESTAMP,
    CONSTRAINT PK_SC_ITEMS        PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_SCI_COUNT       FOREIGN KEY (COUNT_ID)    REFERENCES STOCK_COUNTS(COUNT_ID),
    CONSTRAINT FK_SCI_PRODUCT     FOREIGN KEY (PRODUCT_ID)  REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_SCI_EMPLOYEE    FOREIGN KEY (COUNTED_BY)  REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- ── SEQUENCES FOR NEW TABLES ──────────────────────────────────
CREATE SEQUENCE SUPPLIER_SEQ        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PROD_SUPP_SEQ       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PO_SEQ              START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PO_ITEM_SEQ         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE INV_ADJ_SEQ         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE STOCK_COUNT_SEQ     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE STOCK_COUNT_ITEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ── INDEXES FOR NEW TABLES ────────────────────────────────────
CREATE INDEX IDX_SUPP_TENANT        ON SUPPLIERS (TENANT_ID);
CREATE INDEX IDX_PO_TENANT_DATE     ON PURCHASE_ORDERS (TENANT_ID, ORDER_DATE);
CREATE INDEX IDX_PO_SUPPLIER        ON PURCHASE_ORDERS (SUPPLIER_ID);
CREATE INDEX IDX_PO_STATUS          ON PURCHASE_ORDERS (STATUS, TENANT_ID);
CREATE INDEX IDX_POI_PO             ON PURCHASE_ORDER_ITEMS (PO_ID);
CREATE INDEX IDX_POI_PRODUCT        ON PURCHASE_ORDER_ITEMS (PRODUCT_ID);
CREATE INDEX IDX_ADJ_PRODUCT        ON INVENTORY_ADJUSTMENTS (PRODUCT_ID, TENANT_ID);
CREATE INDEX IDX_ADJ_TENANT_DATE    ON INVENTORY_ADJUSTMENTS (TENANT_ID, CREATED_AT);
CREATE INDEX IDX_SC_TENANT          ON STOCK_COUNTS (TENANT_ID, STARTED_AT);
